---
title: "ClearanceRate_Analysis foodxOA_experiment"
author: "Samuel Gurr"
date: "2/1/2023"
output: pdf_document
---

```{r setup, include=FALSE}
# Purpose: Bay Scallop Project - Feeding Rates
# analysis of respiration rate data

# Written by: Sam J Gurr (last edit 11/17/2022)

# Review Riisgard 2001 defining the clearance rate of bivalves 
# NOTE: clearance rate is defined as the volume of water cleared of suspended particles per unit time, and only equals filtration rate when 
# 100% of suspended particles are efficiently retained

# LOAD PACKAGES :::::::::::::::::::::::::::::::::::::::::::::::::::::::

library(dplyr)
library(ggplot2)
library(forcats)
library(lme4)
library(lmerTest)
library(see)
library(performance)
library(car)
library(reshape2)
library(lubridate)
library(SciViews)
library(reshape2)
library(SciViews)
library(kableExtra)
library(latex2exp)
library(pander)
library(performance)
library(ggpubr)
library(Rmisc)
library(nlme)
library(AICcmodavg)



# SET WORKING DIRECTORY :::::::::::::::::::::::::::::::::::::::::::::::

# setwd("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis") # Work computer
setwd("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis") # personal computer

# LOAD DATA :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Master_data       <- read.csv(file="Data/Clearance_rates/ClearanceRates_MasterData.csv", header=T) # master data file
ClearancRates_calc  <- read.csv(file="Output/ClearanceRates/ClearanceRate_Calc.csv", header=T) # master data file

# what is our N at each timepoint? 
#20210914 - timepoint Day 0
ClearancRates_calc %>% dplyr::filter(Date == '20210914') %>% 
                       summarySE(measurevar="Length_um", 
                                 groupvars=c("Replicate", "pH", "Fed_Unfed")) # N = 3 per replicate
#20210930 - timepoint Day 14
ClearancRates_calc %>% dplyr::filter(Date == '20210930') %>% 
                       summarySE(measurevar="Length_um", 
                                 groupvars=c("Replicate", "pH", "Fed_Unfed")) # N = 4-5 per replicate
#20211026 - timepoint Day 42
ClearancRates_calc %>% dplyr::filter(Date == '20211026') %>% 
                       summarySE(measurevar="Length_um", 
                                 groupvars=c("Replicate", "pH", "Fed_Unfed")) # N = 2-3 per replicate
```











## 20210914 Clearance Rate data 

```{r 20210914 CR DATA SUMMARY, echo = T}


# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# One-way models (Kruskal Wallis for nonparametric if needed) ::::::::::::::::::::::::::::::::::::
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::




# Data - simple size corrected

Total_FR_914_df      <- ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Total_mL.hr.mmlength > 0) %>% mutate(type = 'Total') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Total_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Ply_mL.hr.mmlength','Seston_mL.hr.mmlength')) %>% 
  dplyr::mutate(pH = as.factor(pH))


Ply_FR_914_df      <- ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Ply_mL.hr.mmlength > 0) %>% mutate(type = 'ply') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Ply_mL.hr.mmlength) %>% 
  dplyr::select(!c('Total_mL.hr.mmlength','Chaet_mL.hr.mmlength','Seston_mL.hr.mmlength')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Chaet_FR_914_df    <-  ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Chaet_mL.hr.mmlength > 0) %>% mutate(type = 'chaet') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Chaet_mL.hr.mmlength) %>% 
  dplyr::select(!c('Ply_mL.hr.mmlength', 'Total_mL.hr.mmlength', 'Seston_mL.hr.mmlength')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Seston_FR_914_df   <-  ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Seston_mL.hr.mmlength > 0) %>% mutate(type = 'seston') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Seston_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength', 'Total_mL.hr.mmlength', 'Ply_mL.hr.mmlength')) %>% 
  dplyr::mutate(pH = as.factor(pH))


pander(Total_FR_914_df %>% summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |   ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:------:|
# | 500 μatm |    fed    | 9  |       2.423       | 1.299 | 0.4329 | 0.9983 |
# | 800 μatm |    fed    | 12 |        4.5        | 2.761 | 0.797  | 1.754  |
pander(Ply_FR_914_df %>% summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 6  |       4.384       | 2.509 | 1.024  | 2.634 |
# | 800 μatm |    fed    | 10 |       4.85        | 2.31  | 0.7304 | 1.652 |
pander(Chaet_FR_914_df %>% summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 11 |       2.799       | 1.552 | 0.4681 | 1.043 |
# | 800 μatm |    fed    | 12 |       4.715       | 2.761 | 0.7969 | 1.754 |
pander(Seston_FR_914_df %>% summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |   ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:------:|
# | 500 μatm |    fed    | 11 |       2.54        | 1.289 | 0.3886 | 0.8659 |
# | 800 μatm |    fed    | 12 |       3.59        | 2.23  | 0.6437 | 1.417  |


# Data - b factor normalized

Total_FR_914_df.bfactor      <- ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Total_mL.hr.mmlength > 0) %>% mutate(type = 'Total') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Total_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Ply_mL.hr.bfactor', 'Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))


Ply_FR_914_df.bfactor      <- ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Ply_mL.hr.mmlength > 0) %>% mutate(type = 'ply') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Ply_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Total_mL.hr.bfactor', 'Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Chaet_FR_914_df.bfactor    <-  ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Chaet_mL.hr.mmlength > 0) %>% mutate(type = 'chaet') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Chaet_mL.hr.bfactor) %>% 
  dplyr::select(!c('Ply_mL.hr.bfactor', 'Total_mL.hr.bfactor', 'Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Seston_FR_914_df.bfactor   <-  ClearancRates_calc %>% 
  filter(Date %in% '20210914') %>%   
  filter(Seston_mL.hr.mmlength > 0) %>% mutate(type = 'seston') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Seston_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Total_mL.hr.bfactor', 'Ply_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

((11.02 - 5.47)/11.42)*100 # 48.59895

pander(Total_FR_914_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 9  |       5.47       | 2.246 | 0.7486 | 1.726 |
# | 800 μatm |    fed    | 12 |      11.02       | 6.432 | 1.857  | 4.087 |

pander(Ply_FR_914_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 6  |      10.92       | 6.501 | 2.654 | 6.822 |
# | 800 μatm |    fed    | 10 |      12.29       | 6.136 | 1.94  | 4.389 |
((11.52-6.545)/11.52)*100
pander(Chaet_FR_914_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 11 |      6.545       | 2.92  | 0.8804 | 1.962 |
# | 800 μatm |    fed    | 12 |      11.52       | 6.464 | 1.866  | 4.107 |
pander(Seston_FR_914_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 11 |      6.056       | 2.884 | 0.8694 | 1.937 |
# | 800 μatm |    fed    | 12 |       8.82       | 5.238 | 1.512  | 3.328 |


Master_914_plotting         <- rbind(Total_FR_914_df,
                                      Chaet_FR_914_df, 
                                      Ply_FR_914_df, 
                                      Seston_FR_914_df)
Master_914_plotting$pHxfood <- paste(Master_914_plotting$pCO2, Master_914_plotting$Fed_Unfed, sep = '_')


```

```{r 20210914 CR ANALYSIS, echo = T}



# total  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


# Total - one-way anova
Total_FR_914_df.bfactor_MEAN <- Total_FR_914_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Total_AOVmod_0914            <-aov(CR_mL.hr.bfactor ~ pCO2,
                                   data=Total_FR_914_df.bfactor_MEAN) #nlme
shapiro.test(resid(Total_AOVmod_0914)) # 0.6055
leveneTest(Total_AOVmod_0914) # 0.2651
pander(print(Total_AOVmod_0914), style='rmarkdown') # table for SRH test
# |    &nbsp;     | Df | Sum Sq | Mean Sq | F value | Pr(>F)  |
# |:-------------:|:--:|:------:|:-------:|:-------:|:-------:|
# |   **pCO2**    | 1  |  65.7  |  65.7   |  10.58  | 0.01741 |
# | **Residuals** | 6  | 37.26  |  6.21   |   NA    |   NA    |

kable(as.data.frame(anova(Total_KWmod_0914))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/20210914_Total_CR_OneWayANOVA_Table.png", zoom = 1.5)

# pCO2 diff - report this percent difference alonside the MARGINAL effect
Total_FR_914_df.bfactor_MEAN %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars="pCO2")
perc_diff <- (11.519315 - 6.576001)/11.519315*100
perc_diff #42.91326 %v



# ply :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


# Ply - one-way anova
Ply_FR_914_df.bfactor_MEAN <- Ply_FR_914_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Ply_AOVmod_0914            <-aov(CR_mL.hr.bfactor ~ pCO2,
                                 data=Ply_FR_914_df.bfactor_MEAN) #nlme
shapiro.test(resid(Ply_AOVmod_0914)) # 0.1686
leveneTest(Ply_AOVmod_0914) # 0.3539
pander(anova(Ply_AOVmod_0914), style='rmarkdown') # anova table of lme
# |    &nbsp;     | Df | Sum Sq | Mean Sq | F value | Pr(>F) |
# |:-------------:|:--:|:------:|:-------:|:-------:|:------:|
# |   **pCO2**    | 1  | 1.125  |  1.125  | 0.03592 | 0.8559 |
# | **Residuals** | 6  |  188   |  31.33  |   NA    |   NA   |
kable(as.data.frame(anova(Ply_AOVmod_0914))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/20210914_Ply_CR_OneWayANOVA_Table.png", zoom = 1.5)






# chaet  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# Chaet - one-way anova
Chaet_FR_914_df.bfactor_MEAN <- Chaet_FR_914_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Chaet_AOVmod_0914            <-aov(CR_mL.hr.bfactor ~ pCO2,
                                   data=Chaet_FR_914_df.bfactor_MEAN) #nlme
shapiro.test(resid(Chaet_AOVmod_0914)) # 0.8881
leveneTest(Chaet_AOVmod_0914) #0.3802
pander(print(Chaet_AOVmod_0914), style='rmarkdown') # table for K test
# |    &nbsp;     | Df | Sum Sq | Mean Sq | F value | Pr(>F)  |
# |:-------------:|:--:|:------:|:-------:|:-------:|:-------:|
# |   **pCO2**    | 1  | 48.87  |  48.87  |  7.494  | 0.03385 |
# | **Residuals** | 6  | 39.13  |  6.521  |   NA    |   NA    |
# pCO2 diff - report this percent difference alonside the MARGINAL effect
Chaet_FR_914_df.bfactor_MEAN %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars="pCO2")
perc_diff <- (11.519315 - 6.576001)/11.519315*100
perc_diff #42.91326 %v

kable(as.data.frame(anova(Chaet_AOVmod_0914))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/20210914_Chaet_CR_OneWayANOVA_Table.png", zoom = 1.5)



# seston  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


# Seston - one-way anova
Seston_FR_914_df.bfactor_MEAN <- Seston_FR_914_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Seston_AOVmod_0914            <- aov(CR_mL.hr.bfactor ~ pCO2,
                                     data=Seston_FR_914_df.bfactor_MEAN) #nlme
shapiro.test(resid(Seston_AOVmod_0914)) # 0.9325
leveneTest(Seston_AOVmod_0914) # 0.4152
pander(aov(Seston_AOVmod_0914), style='rmarkdown') # table for SRH test
# |    &nbsp;     | Df | Sum Sq | Mean Sq | F value | Pr(>F) |
# |:-------------:|:--:|:------:|:-------:|:-------:|:------:|
# |   **pCO2**    | 1  | 17.99  |  17.99  |  2.496  | 0.1652 |
# | **Residuals** | 6  | 43.24  |  7.207  |   NA    |   NA   |
kable(as.data.frame(anova(Seston_AOVmod_0914))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/20210914_Seston_CR_OneWayANOVA_Table.png", zoom = 1.5)








# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#  Plots                      ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# simple size corrected data 
Master_914_plotting         <- rbind(Total_FR_914_df, Chaet_FR_914_df, Ply_FR_914_df, Seston_FR_914_df)
Master_914_plotting$pHxfood <- paste(Master_914_plotting$pH, Master_914_plotting$Fed_Unfed, sep = '_')

CR_914_boxplot <- Master_914_plotting %>% 
  ggplot(aes(pCO2 , CR_mL.hr.mmlength , fill = pCO2)) +
  theme(panel.grid=element_blank()) +
  geom_boxplot(size=0.2, alpha=0.1, aes(fill=pCO2)) +
  scale_fill_manual(values=c("white","grey50")) +
  geom_point(shape = 21, size = 2, position = position_jitterdodge(jitter.width = 0.1)) +
  theme_classic() +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=10)) +
  stat_summary(fun.y=mean, geom="point", shape=18, size=4, color="black", fill="white") +
  ggtitle("Clearance rate (size corrected), F1 Scallops 20210914") +
  facet_wrap(~type)
CR_914_boxplot

# b factor normalized data 
Master_914_plotting.bfactor         <- rbind(Total_FR_914_df.bfactor,Chaet_FR_914_df.bfactor, Ply_FR_914_df.bfactor, Seston_FR_914_df.bfactor)
Master_914_plotting.bfactor$pHxfood <- paste(Master_914_plotting.bfactor$pH, Master_914_plotting.bfactor$Fed_Unfed, sep = '_')

CR_914_boxplot.bfactor <- Master_914_plotting.bfactor %>% 
  ggplot(aes(pCO2 , CR_mL.hr.bfactor , fill = pCO2)) +
  theme(panel.grid=element_blank()) +
  geom_boxplot(size=0.2, alpha=0.1, aes(fill=pCO2)) +
  scale_fill_manual(values=c("white","grey50")) +
  geom_point(shape = 21, size = 2, position = position_jitterdodge(jitter.width = 0.1)) +
  theme_classic() +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=10)) +
  stat_summary(fun.y=mean, geom="point", shape=18, size=4, color="black", fill="white") +
  ggtitle("Clearance rate (bfactor normalized), F1 Scallops 20210914") +
  facet_wrap(~type)
CR_914_boxplot.bfactor


# Save plots :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/2010914_CR_Boxplots.pdf"))
ggarrange( )
dev.off()


pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/2010914_CR_Boxplots_bfactor.pdf"))
ggarrange(CR_914_boxplot.bfactor)
dev.off()

```




## 20210930 Clearance Rate data 

```{r 20210930 CR DATA SUMMARY, echo = T}

# Data - simple size corrected

Total_FR_930_df      <- ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Total_mL.hr.mmlength > 0) %>% 
  mutate(type = 'Total') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Total_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Ply_mL.hr.mmlength', 'Seston_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))

Ply_FR_930_df      <- ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Ply_mL.hr.mmlength > 0) %>% 
  mutate(type = 'ply') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Ply_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Total_mL.hr.mmlength', 'Seston_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))

Chaet_FR_930_df    <- ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%   
  filter(Chaet_mL.hr.mmlength > 0) %>% 
  mutate(type = 'chaet') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Chaet_mL.hr.mmlength) %>% 
  dplyr::select(!c('Ply_mL.hr.mmlength','Total_mL.hr.mmlength', 'Seston_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))

Seston_FR_930_df   <- ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Seston_mL.hr.mmlength > 0) %>% 
  mutate(type = 'seston') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Seston_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Total_mL.hr.mmlength', 'Ply_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))


pander(Total_FR_930_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |   ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:------:|
# | 500 μatm |    fed    | 20 |       5.775       | 6.478 | 1.449  | 3.032  |
# | 500 μatm |   unfed   | 16 |       2.191       | 1.871 | 0.4679 | 0.9972 |
# | 800 μatm |    fed    | 18 |       6.413       | 8.15  | 1.921  | 4.053  |
# | 800 μatm |   unfed   | 12 |       1.943       | 1.744 | 0.5034 | 1.108  |
pander(Ply_FR_930_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 13 |       4.416       | 5.617 | 1.558 | 3.394 |
# | 500 μatm |   unfed   | 5  |       3.395       | 4.413 | 1.973 | 5.479 |
# | 800 μatm |    fed    | 11 |       6.803       | 5.429 | 1.637 | 3.647 |
# | 800 μatm |   unfed   | 4  |       2.187       | 2.42  | 1.21  | 3.851 |

pander(Chaet_FR_930_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |   ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:------:|
# | 500 μatm |    fed    | 20 |       6.276       | 6.496 | 1.453  |  3.04  |
# | 500 μatm |   unfed   | 18 |       2.63        | 1.823 | 0.4296 | 0.9064 |
# | 800 μatm |    fed    | 19 |       6.377       | 8.419 | 1.932  | 4.058  |
# | 800 μatm |   unfed   | 11 |       2.349       | 2.319 | 0.6991 | 1.558  |
pander(Seston_FR_930_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 11 |       5.22        | 3.935 | 1.187  | 2.644 |
# | 500 μatm |   unfed   | 15 |       2.773       | 2.687 | 0.6937 | 1.488 |
# | 800 μatm |    fed    | 13 |       3.83        | 4.54  | 1.259  | 2.743 |
# | 800 μatm |   unfed   | 11 |       4.18        | 5.228 | 1.576  | 3.512 |

# Data - b factor normalized
Total_FR_930_df.bfactor      <- ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Total_mL.hr.mmlength > 0) %>% mutate(type = 'Total') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Total_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Ply_mL.hr.bfactor','Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Ply_FR_930_df.bfactor      <- ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Ply_mL.hr.mmlength > 0) %>% mutate(type = 'ply') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Ply_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Total_mL.hr.bfactor', 'Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Chaet_FR_930_df.bfactor    <-  ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Chaet_mL.hr.mmlength > 0) %>% mutate(type = 'chaet') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Chaet_mL.hr.bfactor) %>% 
  dplyr::select(!c('Ply_mL.hr.bfactor','Total_mL.hr.bfactor', 'Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Seston_FR_930_df.bfactor   <-  ClearancRates_calc %>% 
  filter(Date %in% '20210930') %>%  
  filter(Seston_mL.hr.mmlength > 0) %>% mutate(type = 'seston') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Seston_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Total_mL.hr.bfactor', 'Ply_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))


((16.92-8.179)/16.92)*100 # 51.66076
pander(Total_FR_930_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 20 |      15.86       | 15.52 | 3.471 | 7.265 |
# | 500 μatm |   unfed   | 16 |      7.951       | 5.675 | 1.419 | 3.024 |
# | 800 μatm |    fed    | 18 |       18.1       | 19.75 | 4.656 | 9.823 |
# | 800 μatm |   unfed   | 12 |      8.482       | 10.04 | 2.898 | 6.378 |
pander(Ply_FR_930_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 13 |      11.75       | 13.51 | 3.747 | 8.163 |
# | 500 μatm |   unfed   | 5  |      12.34       | 16.71 | 7.474 | 20.75 |
# | 800 μatm |    fed    | 11 |      19.25       | 13.63 | 4.11  | 9.159 |
# | 800 μatm |   unfed   | 4  |      8.455       | 9.576 | 4.788 | 15.24 |
pander(Chaet_FR_930_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 20 |      17.47       | 15.4  | 3.443 | 7.207 |
# | 500 μatm |   unfed   | 18 |      9.824       | 5.763 | 1.358 | 2.866 |
# | 800 μatm |    fed    | 19 |      18.04       | 20.46 | 4.694 | 9.862 |
# | 800 μatm |   unfed   | 11 |      10.39       | 13.64 | 4.113 | 9.164 |

((17.75-10.04)/17.75)*100 # 43.43662
pander(Chaet_FR_930_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=("Fed_Unfed")), style='rmarkdown')
# | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# |    fed    | 39 |      17.75       | 17.8  | 2.851 | 5.771 |
# |   unfed   | 29 |      10.04       | 9.311 | 1.729 | 3.542 |
  
pander(Seston_FR_930_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 11 |      14.58       | 9.516 | 2.869 | 6.393 |
# | 500 μatm |   unfed   | 15 |      11.21       | 11.64 | 3.005 | 6.444 |
# | 800 μatm |    fed    | 13 |      10.81       | 11.24 | 3.116 | 6.79  |
# | 800 μatm |   unfed   | 11 |      19.81       | 30.09 | 9.073 | 20.22 |
```

```{r 20210930 CR analysis, echo = T}


# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Two-way models (Kruskal Wallis for nonparametric if needed) :::::
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# total :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


library(rcompanion)
# Ply - one-way anova
Total_FR_930_df.bfactor_MEAN <- Total_FR_930_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Total_AOVmod_0930            <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                   data=Total_FR_930_df.bfactor_MEAN) 
shapiro.test(resid(Total_AOVmod_0930)) # 0.1223
leveneTest(Total_AOVmod_0930) # 0.6936
pander(print(Total_AOVmod_0930), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df |  Sum Sq   |  Mean Sq  |  F value  | Pr(>F)  |
# |:------------------:|:--:|:---------:|:---------:|:---------:|:-------:|
# |      **pCO2**      | 1  |   28.2    |   28.2    |  0.6387   | 0.4397  |
# |   **Fed_Unfed**    | 1  |   262.7   |   262.7   |   5.948   | 0.03122 |
# | **pCO2:Fed_Unfed** | 1  | 0.0002145 | 0.0002145 | 4.858e-06 | 0.9983  |
# |   **Residuals**    | 12 |   529.9   |   44.16   |    NA     |   NA    |
kable(as.data.frame(anova(Total_AOVmod_0930))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/20210930_Total_CR_OneWayANOVA_Table.png", zoom = 1.5)

# ply :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

library(rcompanion)
# Ply - one-way anova
Ply_FR_930_df.bfactor_MEAN <- Ply_FR_930_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Ply_AOVmod_0930              <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                   data=Ply_FR_930_df.bfactor_MEAN) 
shapiro.test(resid(Ply_AOVmod_0930)) #  0.04916
leveneTest(Ply_AOVmod_0930) # 0.9258
# need to run the non parametric Scheirer-Ray-Hare Test
Ply_SRHmod_0930 <- scheirerRayHare(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                      data=Ply_FR_930_df.bfactor_MEAN)
pander(print(Ply_SRHmod_0930), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq |   H    | p.value |
# |:------------------:|:--:|:------:|:------:|:-------:|
# |      **pCO2**      | 1  |  12.8  | 0.844  | 0.3583  |
# |   **Fed_Unfed**    | 1  | 6.857  | 0.4521 | 0.5013  |
# | **pCO2:Fed_Unfed** | 1  |   12   | 0.7912 | 0.3737  |
# |   **Residuals**    | 9  |  152   |   NA   |   NA    |
kable(as.data.frame(print(Ply_SRHmod_0930))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/20210930_Ply_CR_SRH_Table.png", zoom = 1.5)



# chaet  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# Chaet - one-way anova
Chaet_FR_930_df.bfactor_MEAN <- Chaet_FR_930_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Chaet_AOVmod_0930            <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                   data=Chaet_FR_930_df.bfactor_MEAN) 
shapiro.test(resid(Chaet_AOVmod_0930)) # 0.3312
leveneTest(Chaet_AOVmod_0930) #0.5328
pander(print(Chaet_AOVmod_0930), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq | Mean Sq | F value | Pr(>F)  |
# |:------------------:|:--:|:------:|:-------:|:-------:|:-------:|
# |      **pCO2**      | 1  | 10.02  |  10.02  | 0.2151  | 0.6511  |
# |   **Fed_Unfed**    | 1  | 183.4  |  183.4  |  3.936  | 0.07062 |
# | **pCO2:Fed_Unfed** | 1  | 3.981  |  3.981  | 0.08545 |  0.775  |
# |   **Residuals**    | 12 | 559.1  |  46.59  |   NA    |   NA    |
kable(as.data.frame(anova(Chaet_AOVmod_0930))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/20210930_Chaet_CR_OneWayANOVA_Table.png", zoom = 1.5)



# seston  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# Seston - one-way anova
Seston_FR_930_df.bfactor_MEAN <- Seston_FR_930_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Seston_AOVmod_0930            <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                    data=Seston_FR_930_df.bfactor_MEAN) #nlme
shapiro.test(resid(Seston_AOVmod_0930))# 0.0004351
leveneTest(Seston_AOVmod_0930) # 0.3645 .
# need to run the non parametric Scheirer-Ray-Hare Test
Seston_SRHmod_0930 <- scheirerRayHare(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                      data=Seston_FR_930_df.bfactor_MEAN)
pander(print(Seston_SRHmod_0930), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq |    H    | p.value |
# |:------------------:|:--:|:------:|:-------:|:-------:|
# |      **pCO2**      | 1  |  2.25  | 0.09926 | 0.7527  |
# |   **Fed_Unfed**    | 1  |  2.25  | 0.09926 | 0.7527  |
# | **pCO2:Fed_Unfed** | 1  |   1    | 0.04412 | 0.8336  |
# |   **Residuals**    | 12 | 334.5  |   NA    |   NA    |
kable(as.data.frame(print(Seston_SRHmod_0930))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/20210930_Seston_CR_SRH_Table.png", zoom = 1.5)





# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#  Plots  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::




Master_930_plotting         <- rbind(Total_FR_930_df,Chaet_FR_930_df, Ply_FR_930_df, Seston_FR_930_df)
Master_930_plotting$pHxfood <- paste(Master_930_plotting$pH, Master_930_plotting$Fed_Unfed, sep = '_')
CR_930_boxplot <- Master_930_plotting %>% 
  ggplot(aes(pHxfood , CR_mL.hr.mmlength , fill = pHxfood)) +
  theme(panel.grid=element_blank()) +
  geom_boxplot(size=0.2, alpha=0.1, aes(fill=pHxfood)) +
  scale_fill_manual(values=c("grey50","grey50","white","white")) +
  geom_point(shape = 21, size = 2, position = position_jitterdodge(jitter.width = 0.1)) +
  theme_classic() +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=10)) +
  stat_summary(fun.y=mean, geom="point", shape=18, size=4, color="black", fill="white") +
  ggtitle("Clearance rate, F1 Scallops 20210930") +
  facet_wrap(~type)
CR_930_boxplot


# b factor normalized data 
Master_930_plotting.bfactor         <- rbind(Total_FR_930_df.bfactor,
                                             Chaet_FR_930_df.bfactor, 
                                             Ply_FR_930_df.bfactor, 
                                             Seston_FR_930_df.bfactor)
Master_930_plotting.bfactor$pHxfood <- paste(Master_930_plotting.bfactor$pH, Master_930_plotting.bfactor$Fed_Unfed, sep = '_')

CR_930_boxplot.bfactor <- Master_930_plotting.bfactor %>% 
  ggplot(aes(pHxfood , 
             CR_mL.hr.bfactor , 
             fill = pHxfood)) +
  theme(panel.grid=element_blank()) +
  geom_boxplot(size=0.2, 
               alpha=0.1, 
               aes(fill=pHxfood)) +
  scale_fill_manual(values=c("grey50","grey50","white","white")) +
  geom_point(shape = 21, 
             size = 2, 
             position = position_jitterdodge(jitter.width = 0.1)) +
  theme_classic() +
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=10)) +
  stat_summary(fun.y=mean, 
               geom="point", 
               shape=18, 
               size=4, 
               color="black", 
               fill="white") +
  ggtitle("Clearance rate (bfactor normalized), F1 Scallops 20210930") +
  facet_wrap(~type)
CR_930_boxplot.bfactor


# Save plots :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/2010930_CR_Boxplots.pdf"))
ggarrange(CR_930_boxplot)
dev.off()


pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/2010930_CR_Boxplots_bfactor.pdf"))
ggarrange(CR_930_boxplot.bfactor)
dev.off()

```




## 20211026 Clearance Rate data 


```{r 20211026 CR DATA SUMMARY, echo = T}

# Data - simple size corrected

Total_FR_1026_df      <- ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Total_mL.hr.mmlength > 0) %>% 
  mutate(type = 'Total') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Total_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Ply_mL.hr.mmlength', 'Seston_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))

Ply_FR_1026_df      <- ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Ply_mL.hr.mmlength > 0) %>% 
  mutate(type = 'ply') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Ply_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Total_mL.hr.mmlength', 'Seston_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))

Chaet_FR_1026_df    <- ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%   
  filter(Chaet_mL.hr.mmlength > 0) %>% 
  mutate(type = 'chaet') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Chaet_mL.hr.mmlength) %>% 
  dplyr::select(!c('Ply_mL.hr.mmlength','Total_mL.hr.mmlength','Seston_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))

Seston_FR_1026_df   <- ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Seston_mL.hr.mmlength > 0) %>% 
  mutate(type = 'seston') %>% 
  dplyr::rename(CR_mL.hr.mmlength = Seston_mL.hr.mmlength) %>% 
  dplyr::select(!c('Chaet_mL.hr.mmlength','Total_mL.hr.mmlength','Ply_mL.hr.mmlength'))%>% 
  dplyr::mutate(pH = as.factor(pH))


pander(Total_FR_1026_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |   sd   |   se   |   ci   |
# |:--------:|:---------:|:--:|:-----------------:|:------:|:------:|:------:|
# | 500 μatm |    fed    | 8  |       12.89       | 3.782  | 1.337  | 3.162  |
# | 500 μatm |   unfed   | 2  |      0.8691       | 0.9871 | 0.698  | 8.868  |
# | 800 μatm |    fed    | 10 |       18.17       |  13.8  | 4.364  | 9.872  |
# | 800 μatm |   unfed   | 7  |       1.994       | 1.036  | 0.3917 | 0.9585 |

pander(Ply_FR_1026_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |  sd   |   se   |  ci   |
# |:--------:|:---------:|:--:|:-----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 8  |       41.78       | 19.71 | 6.969  | 16.48 |
# | 500 μatm |   unfed   | 7  |       6.111       | 4.378 | 1.655  | 4.049 |
# | 800 μatm |    fed    | 10 |       42.92       | 37.15 | 11.75  | 26.58 |
# | 800 μatm |   unfed   | 7  |       5.22        | 2.507 | 0.9476 | 2.319 |
pander(Chaet_FR_1026_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.mmlength |   sd   |   se   |   ci   |
# |:--------:|:---------:|:--:|:-----------------:|:------:|:------:|:------:|
# | 500 μatm |    fed    | 8  |       13.03       | 3.827  | 1.353  |  3.2   |
# | 500 μatm |   unfed   | 3  |       1.971       | 0.7464 | 0.4309 | 1.854  |
# | 800 μatm |    fed    | 10 |       18.4        | 13.64  | 4.312  | 9.755  |
# | 800 μatm |   unfed   | 7  |       2.068       |  1.05  | 0.397  | 0.9713 |
pander(Chaet_FR_1026_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=("Fed_Unfed")), style='rmarkdown')
# | Fed_Unfed | N  | CR_mL.hr.mmlength |   sd   |   se   |   ci   |
# |:---------:|:--:|:-----------------:|:------:|:------:|:------:|
# |    fed    | 18 |       16.01       | 10.58  | 2.495  | 5.264  |
# |   unfed   | 10 |       2.039       | 0.9281 | 0.2935 | 0.6639 |
  
pander(Seston_FR_1026_df %>% 
         summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N | CR_mL.hr.mmlength |  sd   |   se   |  ci   |
# |:--------:|:---------:|:-:|:-----------------:|:-----:|:------:|:-----:|
# | 500 μatm |    fed    | 8 |       7.572       | 3.019 | 1.067  | 2.524 |
# | 500 μatm |   unfed   | 6 |       2.738       | 1.533 | 0.6257 | 1.608 |
# | 800 μatm |    fed    | 9 |       11.79       | 5.907 | 1.969  | 4.541 |
# | 800 μatm |   unfed   | 6 |       1.875       | 1.633 | 0.6667 | 1.714 |





# Data - b factor normalized
Total_FR_1026_df.bfactor      <- ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Total_mL.hr.mmlength > 0) %>% mutate(type = 'Total') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Total_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Ply_mL.hr.bfactor','Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Ply_FR_1026_df.bfactor      <- ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Ply_mL.hr.mmlength > 0) %>% mutate(type = 'ply') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Ply_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Total_mL.hr.bfactor','Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Chaet_FR_1026_df.bfactor    <-  ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Chaet_mL.hr.mmlength > 0) %>% mutate(type = 'chaet') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Chaet_mL.hr.bfactor) %>% 
  dplyr::select(!c('Ply_mL.hr.bfactor','Total_mL.hr.bfactor','Seston_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))

Seston_FR_1026_df.bfactor   <-  ClearancRates_calc %>% 
  filter(Date %in% '20211026') %>%  
  filter(Seston_mL.hr.mmlength > 0) %>% mutate(type = 'seston') %>% 
  dplyr::rename(CR_mL.hr.bfactor = Seston_mL.hr.bfactor) %>% 
  dplyr::select(!c('Chaet_mL.hr.bfactor','Total_mL.hr.bfactor','Ply_mL.hr.bfactor')) %>% 
  dplyr::mutate(pH = as.factor(pH))



pander(Total_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2","Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 8  |      64.04       | 23.74 | 8.393 | 19.85 |
# | 500 μatm |   unfed   | 2  |      15.66       | 17.87 | 12.64 | 160.6 |
# | 800 μatm |    fed    | 10 |      100.9       | 64.98 | 20.55 | 46.48 |
# | 800 μatm |   unfed   | 7  |      25.16       | 14.89 | 5.627 | 13.77 |
((84.52-23.05)/84.52)*100 # 72.72835
pander(Total_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("Fed_Unfed")), style='rmarkdown')
# | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# |    fed    | 18 |      84.52       | 53.13 | 12.52 | 26.42 |
# |   unfed   | 9  |      23.05       | 14.96 | 4.986 | 11.5  |


pander(Ply_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2","Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 8  |      203.9       | 102.4 | 36.2  | 85.61 |
# | 500 μatm |   unfed   | 7  |       98.7       | 81.56 | 30.83 | 75.43 |
# | 800 μatm |    fed    | 10 |      244.8       | 213.2 | 67.42 | 152.5 |
# | 800 μatm |   unfed   | 7  |      65.34       | 35.15 | 13.29 | 32.51 |
((226.6 -82.02 )/226.6)*100 # 63.80406
pander(Ply_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("Fed_Unfed")), style='rmarkdown')
# | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# |    fed    | 18 |      226.6       | 169.8 | 40.01 | 84.42 |
# |   unfed   | 14 |      82.02       | 62.77 | 16.78 | 36.24 |


pander(Chaet_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 8  |      64.74       | 24.11 | 8.525 | 20.16 |
# | 500 μatm |   unfed   | 3  |      33.45       | 16.23 | 9.371 | 40.32 |
# | 800 μatm |    fed    | 10 |      102.3       | 63.87 | 20.2  | 45.69 |
# | 800 μatm |   unfed   | 7  |      25.87       | 15.19 | 5.742 | 14.05 |

((85.59 -28.14)/85.59)*100 # 67.12233
pander(Chaet_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=("Fed_Unfed")), style='rmarkdown')
# | Fed_Unfed | N  | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:---------:|:--:|:----------------:|:-----:|:-----:|:-----:|
# |    fed    | 18 |      85.59       | 52.6  | 12.4  | 26.16 |
# |   unfed   | 10 |      28.14       | 15.03 | 4.752 | 10.75 |
  
pander(Seston_FR_1026_df.bfactor %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:-:|:----------------:|:-----:|:-----:|:-----:|
# | 500 μatm |    fed    | 8 |      38.09       | 18.68 | 6.604 | 15.62 |
# | 500 μatm |   unfed   | 6 |      38.61       | 19.13 | 7.81  | 20.08 |
# | 800 μatm |    fed    | 9 |      69.81       | 39.06 | 13.02 | 30.02 |
# | 800 μatm |   unfed   | 6 |       22.5       | 19.96 | 8.147 | 20.94 |



Master_1026_plotting         <- rbind(Total_FR_1026_df,
                                      Chaet_FR_1026_df, 
                                      Ply_FR_1026_df, 
                                      Seston_FR_1026_df)
Master_1026_plotting$pHxfood <- paste(Master_1026_plotting$pCO2, Master_1026_plotting$Fed_Unfed, sep = '_')


```

```{r 20211026 CR analysis, echo = T}

# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Two-way models (Kruskal Wallis for nonparametric if needed) :::::
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



library(rcompanion)

# total :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# 0.1277
# Total - one-way anova
Total_FR_1026_df.bfactor_MEAN <- Total_FR_1026_df.bfactor %>% 
  summarySE(measurevar="CR_mL.hr.bfactor", 
            groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Total_AOVmod_1026 <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                      data=Total_FR_1026_df.bfactor_MEAN) 
shapiro.test(resid(Total_AOVmod_1026)) # 0.417
leveneTest(Total_AOVmod_1026) # 0.9283

pander(print(Total_AOVmod_1026), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:------------------:|:--:|:------:|:-------:|:-------:|:---------:|
# |      **pCO2**      | 1  | 289.1  |  289.1  |  2.089  |  0.1823   |
# |   **Fed_Unfed**    | 1  | 13034  |  13034  |  94.16  | 4.594e-06 |
# | **pCO2:Fed_Unfed** | 1  |  441   |   441   |  3.186  |  0.1079   |
# |   **Residuals**    | 9  |  1246  |  138.4  |   NA    |    NA     |
  kable(as.data.frame(anova(Total_AOVmod_1026))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_Total_CR_Twowayanova_Table.png", zoom = 1.5)
  
print(Total_FR_1026_df.bfactor_MEAN %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=("Fed_Unfed")))

# fed 	8	83.09019	23.39664	8.271961	19.56008
# unfed	5	23.91014	10.02891	4.485065	12.45254
# ((83.09019-23.91014)/83.09019)*100 # 71.22387

  
  
  
  
# ply ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  
  
  
  
# Ply - one-way anova
Ply_FR_1026_df.bfactor_MEAN <- Ply_FR_1026_df.bfactor %>% 
                                summarySE(measurevar="CR_mL.hr.bfactor", 
                                          groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Ply_AOVmod_1026             <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                   data=Ply_FR_1026_df.bfactor_MEAN) 
shapiro.test(resid(Ply_AOVmod_1026)) # 0.7939
leveneTest(Ply_AOVmod_1026) # 0.4584
pander(print(Ply_AOVmod_1026), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq | Mean Sq | F value  |  Pr(>F)   |
# |:------------------:|:--:|:------:|:-------:|:--------:|:---------:|
# |      **pCO2**      | 1  | 20.07  |  20.07  | 0.005925 |  0.9399   |
# |   **Fed_Unfed**    | 1  | 79147  |  79147  |  23.36   | 0.0004096 |
# | **pCO2:Fed_Unfed** | 1  |  3944  |  3944   |  1.164   |  0.3018   |
# |   **Residuals**    | 12 | 40655  |  3388   |    NA    |    NA     |
kable(as.data.frame(anova(Ply_AOVmod_1026))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_Ply_CR_Twowayanova_Table.png", zoom = 1.5)

print(Ply_FR_1026_df.bfactor_MEAN %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=("Fed_Unfed")))

# fed	  8	220.72887	57.46115	20.31559	48.03873
# unfed	8	80.06365	55.42784	19.59670	46.33883
((220.72887-80.06365)/220.72887)*100 # 63.7276





# chaet  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# Chaet - two-way anova
Chaet_FR_1026_df.bfactor_MEAN <- Chaet_FR_1026_df.bfactor %>% 
                                  summarySE(measurevar="CR_mL.hr.bfactor", 
                                            groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Chaet_AOVmod_1026             <-aov(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                    data=Chaet_FR_1026_df.bfactor_MEAN) 
shapiro.test(resid(Chaet_AOVmod_1026)) # 0.7287
leveneTest(Chaet_AOVmod_1026) # 0.6625
pander(print(Chaet_AOVmod_1026), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq | Mean Sq | F value |  Pr(>F)  |
# |:------------------:|:--:|:------:|:-------:|:-------:|:--------:|
# |      **pCO2**      | 1  | 510.3  |  510.3  |  3.233  |  0.1024  |
# |   **Fed_Unfed**    | 1  | 12290  |  12290  |  77.87  | 4.94e-06 |
# | **pCO2:Fed_Unfed** | 1  |  1361  |  1361   |  8.624  | 0.01487  |
# |   **Residuals**    | 10 |  1578  |  157.8  |   NA    |    NA    |

kable(as.data.frame(anova(Chaet_AOVmod_1026))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_Chaet_CR_Twowayanova_Table.png", zoom = 1.5)


TukeyHSD(aov(Chaet_AOVmod_1026))
# $`pCO2:Fed_Unfed`
#                                     diff        lwr        upr     p adj
# 800 ?atm:fed-500 ?atm:fed      38.819952   11.64189  65.998014 0.0064054 here
# 500 ?atm:unfed-500 ?atm:fed   -35.971204  -69.25740  -2.685011 0.0337591 here
# 800 ?atm:unfed-500 ?atm:fed   -38.400747  -65.57881 -11.222684 0.0068814 here
# 500 ?atm:unfed-800 ?atm:fed   -74.791156 -108.07735 -41.504963 0.0002113 here
# 800 ?atm:unfed-800 ?atm:fed   -77.220698 -104.39876 -50.042636 0.0000281 here
# 800 ?atm:unfed-500 ?atm:unfed  -2.429543  -35.71574  30.856650 0.9958118
library(emmeans) # posthoc letters!
Chaet_1026_emmeans <- emmeans(Chaet_AOVmod_1026, pairwise ~ pCO2:Fed_Unfed)
Chaet_1026_emmeans
 # contrast                        estimate    SE df t.ratio p.value
 # 500 ?atm fed - 800 ?atm fed       -38.82  8.88 10  -4.370  0.0064
 # 500 ?atm fed - 500 ?atm unfed      35.97 10.88 10   3.306  0.0338
 # 500 ?atm fed - 800 ?atm unfed      38.40  8.88 10   4.323  0.0069
 # 800 ?atm fed - 500 ?atm unfed      74.79 10.88 10   6.874  0.0002
 # 800 ?atm fed - 800 ?atm unfed      77.22  8.88 10   8.693  <.0001
 # 500 ?atm unfed - 800 ?atm unfed     2.43 10.88 10   0.223  0.9958
multcomp::cld(object = Chaet_1026_emmeans$emmeans,Letters = letters)
 # pCO2     Fed_Unfed emmean   SE df lower.CL upper.CL .group
 # 800 atm unfed       26.3 6.28 10    12.35     40.3  a    
 # 500 atm unfed       28.8 8.88 10     8.98     48.6  a    
 # 500 atm fed         64.7 6.28 10    50.75     78.7   b   
 # 800 atm fed        103.6 6.28 10    89.57    117.6    c  


kable(as.data.frame(print(Chaet_FR_1026_df.bfactor_MEAN %>% 
        summarySE(measurevar="CR_mL.hr.bfactor", groupvars=c("pCO2","Fed_Unfed") )))) %>% 
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_Chaet_posthoc_Summary.png", zoom = 1.5)
  

# look at the data - percent difference - the posthoc effect
pander(Chaet_FR_1026_df.bfactor_MEAN %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", 
                   groupvars=c("pCO2", "Fed_Unfed")), style='rmarkdown')
# |   pCO2   | Fed_Unfed | N | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:--------:|:---------:|:-:|:----------------:|:-----:|:-----:|:-----:|
# | 500 ?atm |    fed    | 4 |      64.74       | 10.29 | 5.146 | 16.38 |
# | 500 ?atm |   unfed   | 2 |      28.77       | 19.85 | 14.04 | 178.4 |
# | 800 ?atm |    fed    | 4 |      79.36       | 46.67 | 23.33 | 74.26 | 
# | 800 ?atm |   unfed   | 4 |      26.34       | 6.628 | 3.314 | 10.55 | 
((79.36-64.74)/79.36)*100 # 18.42238 % higher clearance of chaet B by high OA high food than low OA high food
((79.36-28.77)/79.36)*100 # 63.74748
((79.36-26.34)/79.36)*100 # 66.80948


# the food effect
pander(Chaet_FR_1026_df.bfactor_MEAN %>% 
         summarySE(measurevar="CR_mL.hr.bfactor", 
                   groupvars=c("Fed_Unfed")), style='rmarkdown')
# | Fed_Unfed | N | CR_mL.hr.bfactor |  sd   |  se   |  ci   |
# |:---------:|:-:|:----------------:|:-----:|:-----:|:-----:|
# |    fed    | 8 |      84.15       | 24.1  | 8.521 | 20.15 |
# |   unfed   | 6 |      27.15       | 10.33 | 4.218 | 10.84 |
((84.15-27.15)/84.15)*100 # 67.73619
84.15/27.15

# seston  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# Seston - two-way anova
Seston_FR_1026_df.bfactor_MEAN <- Seston_FR_1026_df.bfactor %>% summarySE(measurevar="CR_mL.hr.bfactor", groupvars=(c("Replicate", "Fed_Unfed", "pCO2")))
Seston_AOVmod_1026             <-lm(CR_mL.hr.bfactor ~ pCO2 * Fed_Unfed,
                                    data=Seston_FR_1026_df.bfactor_MEAN) #nlme
shapiro.test(resid(Seston_AOVmod_1026))# 0.3258
leveneTest(Seston_AOVmod_1026) # 0.1911
pander(aov(Seston_AOVmod_1026), style='rmarkdown') # table for SRH test
# |       &nbsp;       | Df | Sum Sq | Mean Sq | F value | Pr(>F)  |
# |:------------------:|:--:|:------:|:-------:|:-------:|:-------:|
# |      **pCO2**      | 1  |  148   |   148   | 0.3303  | 0.5771  |
# |   **Fed_Unfed**    | 1  |  1802  |  1802   |  4.021  | 0.07016 |
# | **pCO2:Fed_Unfed** | 1  |  1618  |  1618   |  3.611  | 0.08392 |
# |   **Residuals**    | 11 |  4930  |  448.1  |   NA    |   NA    |
kable(as.data.frame(anova(Seston_AOVmod_1026))) %>%  # print a png of this table
  kable_styling() %>%
  save_kable(file = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_Seston_CR_Twowayanova_Table.png", zoom = 1.5)


# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#  Plots  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



CR_1026_boxplot              <- Master_1026_plotting %>% 
                                      ggplot(aes(pHxfood , CR_mL.hr.mmlength , fill = pHxfood)) +
                                      theme(panel.grid=element_blank()) +
                                      geom_boxplot(size=0.2, alpha=0.1, aes(fill=pHxfood)) +
                                      scale_fill_manual(values=c("grey50","grey50","white","white")) +
                                      geom_point(shape = 21, size = 2, position = position_jitterdodge(jitter.width = 0.1)) +
                                      theme_classic() +
                                      theme(axis.text=element_text(size=12),
                                            axis.title=element_text(size=10)) +
                                      stat_summary(fun.y=mean, geom="point", shape=18, size=4, color="black", fill="white") +
                                      ggtitle("Clearance rate, F1 Scallops 20211026") +
                                      facet_wrap(~type)
CR_1026_boxplot


# b factor normalized data 
Master_1026_plotting.bfactor         <- rbind(Total_FR_1026_df.bfactor,
                                              Chaet_FR_1026_df.bfactor, 
                                             Ply_FR_1026_df.bfactor, 
                                             Seston_FR_1026_df.bfactor)
Master_1026_plotting.bfactor$pHxfood <- paste(Master_1026_plotting.bfactor$pCO2, Master_1026_plotting.bfactor$Fed_Unfed, sep = '_')

CR_1026_boxplot.bfactor <- Master_1026_plotting.bfactor %>% 
                              ggplot(aes(pHxfood , 
                                         CR_mL.hr.bfactor , 
                                         fill = pHxfood)) +
                              theme(panel.grid=element_blank()) +
                              geom_boxplot(size=0.2, 
                                           alpha=0.1, 
                                           aes(fill=pHxfood)) +
                              scale_fill_manual(values=c("grey50","grey50","white","white")) +
                              geom_point(shape = 21, 
                                         size = 2, 
                                         position = position_jitterdodge(jitter.width = 0.1)) +
                              theme_classic() +
                              theme(axis.text=element_text(size=12),
                                    axis.title=element_text(size=10)) +
                              stat_summary(fun.y=mean, 
                                           geom="point", 
                                           shape=18, 
                                           size=4, 
                                           color="black", 
                                           fill="white") +
                              ggtitle("Clearance rate (bfactor normalized), F1 Scallops 20211026") +
                              facet_wrap(~type)
CR_1026_boxplot.bfactor


# Save plots :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_CR_Boxplots.pdf"))
ggarrange(CR_1026_boxplot)
dev.off()


pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_CR_Boxplots_bfactor.pdf"))
ggarrange(CR_1026_boxplot.bfactor)
dev.off()



CR_1026_Seston.bfactor <- Master_1026_plotting.bfactor %>% 
                              dplyr::filter(type%in%'chaet') %>% 
                                  ggplot(aes(Fed_Unfed, 
                                             CR_mL.hr.bfactor , 
                                             fill = pH,
                                             group = pHxfood)) +
                                  geom_boxplot(size=0.2, 
                                               alpha=0.1, 
                                               aes(fill=pH)) +
                                  scale_fill_manual(values=c("grey50","grey50","white","white")) +#geom_point(posit+
                                  geom_point(position = position_jitterdodge(jitter.width = 0.1)) +
                                  # geom_line(aes(Fed_Unfed)) +
                                  theme_classic() +
                                  theme(axis.text=element_text(size=12),
                                        axis.title=element_text(size=10)) +
                                  ggtitle("Clearance rate (bfactor normalized), F1 Scallops 20211026") 
CR_1026_Seston.bfactor


```


## Plotting

```{r, Chaet ClearanceRate Figure All} 


chaet_clearance_master <- rbind(Chaet_FR_914_df,Chaet_FR_930_df, Chaet_FR_1026_df)



# Length_um
SumTable_ChaetClear <- chaet_clearance_master[!is.na(chaet_clearance_master$CR_mL.hr.mmlength),] %>%  
                          dplyr::mutate(pCO2 = case_when(pH == 8 ~ "500 μatm",  pH == 7.5 ~ "800 μatm")) %>% 
                          summarySE(measurevar="CR_mL.hr.mmlength", 
                                    groupvars=c("Date", "pCO2", "Fed_Unfed")) %>% 
                          dplyr::mutate(Age = case_when(Date == '20210914' ~ 50, 
                                                        Date == '20210930' ~ 66, 
                                                        Date == '20211026' ~ 92)) 
SumTable_ChaetClear$pCO2 <- factor(SumTable_ChaetClear$pCO2, c("500 μatm","800 μatm"))
## Use geom_line and geom_point to plot over time
ChaetClear_time    <- ggplot(data=SumTable_ChaetClear, aes(x=Age, y=CR_mL.hr.mmlength, color=pCO2)) +
                              geom_line(aes(linetype = factor(Fed_Unfed)), size = 0.5) +  
                              geom_point()+ 
                              scale_color_manual(values=c("forestgreen","darkorange2"))+
                              geom_errorbar(aes(ymin=CR_mL.hr.mmlength-se, ymax=CR_mL.hr.mmlength+se), width=.2,
                                            position=position_dodge(.1))+
                              theme_bw() +  
                              theme(panel.grid.major = element_blank(), 
                                    panel.grid.minor = element_blank(), 
                                    plot.title = element_text(size=10)) + 
                              labs(y = expression(mL^{-1}~mm^{-1}%.%hr^{-1})) +
                              scale_x_continuous(name ="Age (d)") +
                              labs(title =  "Clearance of Chaetocerous over time..", 
                                   y = "Clearance rate") +
                              scale_linetype_manual(values = c("fed" = "solid", "unfed" = "dashed"))  +
                              theme(legend.position="none") +
                              # facet_wrap(~factor(Fed_Unfed, level = c('Low food', 'High food'))) 
                              facet_wrap(~pCO2)
ChaetClear_time


ChaetClear_time    <- SumTable_ChaetClear %>% 
                  ggplot(aes(x = factor(Age), 
                             y = CR_mL.hr.mmlength, 
                             fill = pCO2)) +
                  geom_boxplot(alpha = 0.5, # color hue
                             width=0.6, # boxplot width
                             outlier.size=0) +# make outliers small
                  scale_color_manual(values=c("forestgreen","darkorange2"))+
                  geom_errorbar(aes(ymin=CR_mL.hr.mmlength-se, ymax=CR_mL.hr.mmlength+se), width=.2,
                                position=position_dodge(.1))+
                  theme_bw() +  
                  theme(panel.grid.major = element_blank(), 
                        panel.grid.minor = element_blank(), 
                        plot.title = element_text(size=10)) + 
                  labs(y = expression(mL^{-1}~mm^{-1}%.%hr^{-1})) +
                  scale_x_continuous(name ="Age (d)") +
                  labs(title =  "Clearance of Chaetocerous over time..", 
                       y = "Shell length (mm)") +
                  scale_linetype_manual(values = c("fed" = "solid", "unfed" = "dashed"))  +
                  theme(legend.position="none") +
                  # facet_wrap(~factor(Fed_Unfed, level = c('Low food', 'High food'))) 
                  facet_wrap(~pCO2)
ChaetClear_time

pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/Chaet_ClearanceRate_length.pdf"), width = 8, height = 6)
ChaetClear_time
dev.off()
```


```{r, Ply ClearanceRate Figure All} 


Ply_clearance_master <- rbind(Ply_FR_914_df,Ply_FR_930_df, Ply_FR_1026_df)



# Length_um
SumTable_PlyClear <- Ply_clearance_master[!is.na(Ply_clearance_master$CR_mL.hr.mmlength),] %>%  
            summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("Date", "pCO2", "Fed_Unfed")) %>% 
            dplyr::mutate(Age = case_when(Date == '20210914' ~ 50, Date == '20210930' ~ 66, Date == '20211026' ~ 92)) 
SumTable_PlyClear$pCO2 <- factor(SumTable_PlyClear$pCO2, c("500 μatm","800 μatm"))
## Use geom_line and geom_point to plot over time
PlyClear_time    <- ggplot(data=SumTable_PlyClear, aes(x=Age, y=CR_mL.hr.mmlength, color=pCO2)) +
            geom_line(aes(linetype = factor(Fed_Unfed)), size = 0.5) +  
            geom_point()+ 
            scale_color_manual(values=c("forestgreen","darkorange2"))+
            geom_errorbar(aes(ymin=CR_mL.hr.mmlength-se, ymax=CR_mL.hr.mmlength+se), width=.2,
                          position=position_dodge(.1))+
            theme_bw() +  
            theme(panel.grid.major = element_blank(), 
                  panel.grid.minor = element_blank(), 
                  plot.title = element_text(size=10)) + 
            labs(y = expression(mL^{-1}~mm^{-1}%.%hr^{-1})) +
            scale_x_continuous(name ="Age (d)") +
            labs(title =  "Clearance of Plyocerous over time..", 
                 y = "Shell length (mm)") +
            scale_linetype_manual(values = c("fed" = "solid", "unfed" = "dashed"))  +
            theme(legend.position="none") +
            # facet_wrap(~factor(Fed_Unfed, level = c('Low food', 'High food'))) 
            facet_wrap(~pCO2)
PlyClear_time


pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/Ply_ClearanceRate_length.pdf"), width = 8, height = 6)
PlyClear_time
dev.off()
```


```{r, Seston ClearanceRate Figure All} 


Seston_clearance_master <- rbind(Seston_FR_914_df,Seston_FR_930_df, Seston_FR_1026_df)



# Length_um
SumTable_SestonClear <- Seston_clearance_master[!is.na(Seston_clearance_master$CR_mL.hr.mmlength),] %>%  
            summarySE(measurevar="CR_mL.hr.mmlength", groupvars=c("Date", "pCO2", "Fed_Unfed")) %>% 
            dplyr::mutate(Age = case_when(Date == '20210914' ~ 50, Date == '20210930' ~ 66, Date == '20211026' ~ 92)) 
SumTable_SestonClear$pCO2 <- factor(SumTable_SestonClear$pCO2, c("500 μatm","800 μatm"))
## Use geom_line and geom_point to plot over time
SestonClear_time    <- ggplot(data=SumTable_SestonClear, aes(x=Age, y=CR_mL.hr.mmlength, color=pCO2)) +
            geom_line(aes(linetype = factor(Fed_Unfed)), size = 0.5) +  
            geom_point()+ 
            scale_color_manual(values=c("forestgreen","darkorange2"))+
            geom_errorbar(aes(ymin=CR_mL.hr.mmlength-se, ymax=CR_mL.hr.mmlength+se), width=.2,
                          position=position_dodge(.1))+
            theme_bw() +  
            theme(panel.grid.major = element_blank(), 
                  panel.grid.minor = element_blank(), 
                  plot.title = element_text(size=10)) + 
            labs(y = expression(mL^{-1}~mm^{-1}%.%hr^{-1})) +
            scale_x_continuous(name ="Age (d)") +
            labs(title =  "Clearance of Sestonocerous over time..", 
                 y = "Shell length (mm)") +
            scale_linetype_manual(values = c("fed" = "solid", "unfed" = "dashed"))  +
            theme(legend.position="none") +
            # facet_wrap(~factor(Fed_Unfed, level = c('Low food', 'High food'))) 
            facet_wrap(~pCO2)
SestonClear_time


pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/Seston_ClearanceRate_length.pdf"), width = 8, height = 6)
SestonClear_time
dev.off()
```


## Density plots


```{r, 20210930 Density plots }
library(dplyr)
library(tidyr)

# Master_914_plotting <- ClearancRates_calc %>% dplyr::filter(Date %in% '20210914') %>% mutate(pHxfood = paste(pH, Fed_Unfed, sep = "_"))
CHAET_plotting      <- Master_914_plotting %>% dplyr::filter(type %in% 'chaet')
PLY_plotting        <- Master_914_plotting %>% dplyr::filter(type %in% 'ply')
SESTON_plotting     <- Master_914_plotting %>% dplyr::filter(type %in% 'seston')



# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Chaetoceros                  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Master_914_plotting$pHxfood <- as.factor(Master_914_plotting$pHxfood)

# simply corrected for shell length
df_mean_CHAET <- Master_914_plotting %>%
                    dplyr::group_by(pHxfood) %>% 
                    dplyr::summarize(average = mean(Chaet_mL.hr.bfactor)) %>%
                    dplyr::ungroup()
p.box_CHAET <- ggplot(Master_914_plotting, aes(x = pHxfood, y = Chaet_mL.hr.bfactor)) + geom_boxplot() + geom_point(data= df_mean_CHAET, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.CHAET <- layer_data(p.box_CHAET) %>%
                        select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
                        dplyr::rename(mean = flipped_aes) %>% 
                        dplyr::mutate(mean  = df_mean_CHAET$average) %>% 
                        mutate(pHxfood = factor(x, labels = levels(Master_914_plotting$pHxfood), ordered = TRUE)) %>%
                        select(-x)

p.box.data.CHAET %>% unnest(outliers)


density.plot_CR_CHAET_914 <-ggplot(p.box.data.CHAET) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = Master_914_plotting, aes(x = Chaet_mL.hr.bfactor, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                xlim(0, 30) +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (Chaetoceros) 50 DPF", 
                                     x = expression(Clearance~rate~"("~Chaetoceros~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey85", "grey40"))
density.plot_CR_CHAET_914


pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210914_figs_tables/20210914_CR_CHAET_density_plot.pdf"), width = 5, height = 5)
density.plot_CR_CHAET_914 # print the model diagnostics 
dev.off()



```


```{r, 20210930 Density plots }
library(dplyr)
library(tidyr)

Master_930_plotting <- ClearancRates_calc %>% dplyr::filter(Date %in% '20210930') %>% mutate(pHxfood = paste(pH, Fed_Unfed, sep = "_"))
CHAET_plotting      <- Master_930_plotting %>% dplyr::filter(type %in% 'chaet')
PLY_plotting        <- Master_930_plotting %>% dplyr::filter(type %in% 'ply')
SESTON_plotting     <- Master_930_plotting %>% dplyr::filter(type %in% 'seston')



# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Chaetoceros                  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Master_930_plotting$pHxfood <- as.factor(Master_930_plotting$pHxfood)

# simply corrected for shell length
df_mean_CHAET <- Master_930_plotting %>%
  dplyr::group_by(pHxfood) %>% 
  dplyr::summarize(average = mean(Chaet_mL.hr.mmlength)) %>%
  dplyr::ungroup()
p.box_CHAET <- ggplot(Master_930_plotting, aes(x = pHxfood, y = Chaet_mL.hr.mmlength)) + geom_boxplot() + geom_point(data= df_mean_CHAET, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.CHAET <- layer_data(p.box_CHAET) %>%
  select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
  dplyr::rename(mean = flipped_aes) %>% 
  dplyr::mutate(mean  = df_mean_CHAET$average) %>% 
  mutate(pHxfood = factor(x, labels = levels(Master_930_plotting$pHxfood), ordered = TRUE)) %>%
  select(-x)

p.box.data.CHAET %>% unnest(outliers)


density.plot_CR_CHAET_930 <-ggplot(p.box.data.CHAET) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = Master_930_plotting, aes(x = Chaet_mL.hr.mmlength, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (Chaetoceros) 92 DPF", 
                                     x = expression(Clearance~rate~"("~Chaetoceros~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey40", "grey40", "grey85", "grey85"))
density.plot_CR_CHAET_930




# corrected for b factor 

df_mean_CHAET <- Master_930_plotting %>%
  dplyr::group_by(pHxfood) %>% 
  dplyr::summarize(average = mean(Chaet_mL.hr.bfactor)) %>%
  dplyr::ungroup()
p.box_CHAET <- ggplot(Master_930_plotting, aes(x = pHxfood, y = Chaet_mL.hr.bfactor)) + geom_boxplot() + geom_point(data= df_mean_CHAET, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.CHAET <- layer_data(p.box_CHAET) %>%
  select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
  dplyr::rename(mean = flipped_aes) %>% 
  dplyr::mutate(mean  = df_mean_CHAET$average) %>% 
  mutate(pHxfood = factor(x, labels = levels(Master_930_plotting$pHxfood), ordered = TRUE)) %>%
  select(-x)

p.box.data.CHAET %>% unnest(outliers)


density.plot_CR_CHAET_930 <-ggplot(p.box.data.CHAET) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = Master_930_plotting, aes(x = Chaet_mL.hr.bfactor, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (Chaetoceros) 92 DPF", 
                                     x = expression(Clearance~rate~"("~Chaetoceros~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey40", "grey40", "grey85", "grey85"))
density.plot_CR_CHAET_930



pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20210930_figs_tables/20210930_CR_CHAET_density_plot.pdf"), width = 5, height = 5)
density.plot_CR_CHAET_930 # print the model diagnostics 
dev.off()



```

```{r, 20211026 Density plots }
library(dplyr)
library(tidyr)

Master_1026_plotting$pHxfood <- as.factor(Master_1026_plotting$pHxfood)
CHAET_plotting   <- Master_1026_plotting %>% dplyr::filter(type %in% 'chaet')
PLY_plotting     <- Master_1026_plotting %>% dplyr::filter(type %in% 'ply')
SESTON_plotting  <- Master_1026_plotting %>% dplyr::filter(type %in% 'seston')



# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Chaetoceros                  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

df_mean_CHAET <- CHAET_plotting %>%
  dplyr::group_by(pHxfood) %>% 
  dplyr::summarize(average = mean(CR_mL.hr.mmlength)) %>%
  dplyr::ungroup()
p.box_CHAET <- ggplot(CHAET_plotting, aes(x = pHxfood, y = CR_mL.hr.mmlength)) + geom_boxplot() + geom_point(data= df_mean_CHAET, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.CHAET <- layer_data(p.box_CHAET) %>%
  select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
  dplyr::rename(mean = flipped_aes) %>% 
  dplyr::mutate(mean  = df_mean_CHAET$average) %>% 
  mutate(pHxfood = factor(x, labels = levels(CHAET_plotting$pHxfood), ordered = TRUE)) %>%
  select(-x)

p.box.data.CHAET %>% unnest(outliers)


density.plot_CR_CHAET_1026 <-ggplot(p.box.data.CHAET) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = CHAET_plotting, aes(x = CR_mL.hr.mmlength, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (Chaetoceros) 92 DPF", 
                                     x = expression(Clearance~rate~"("~Chaetoceros~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey40", "grey40", "grey85", "grey85"))
density.plot_CR_CHAET_1026



# b factor 
df_mean_CHAET <- CHAET_plotting %>%
  dplyr::group_by(pHxfood) %>% 
  dplyr::summarize(average = mean(Chaet_mL.hr.bfactor)) %>%
  dplyr::ungroup()
p.box_CHAET <- ggplot(CHAET_plotting, aes(x = pHxfood, y = Chaet_mL.hr.bfactor)) + geom_boxplot() + geom_point(data= df_mean_CHAET, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.CHAET <- layer_data(p.box_CHAET) %>%
  select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
  dplyr::rename(mean = flipped_aes) %>% 
  dplyr::mutate(mean  = df_mean_CHAET$average) %>% 
  mutate(pHxfood = factor(x, labels = levels(CHAET_plotting$pHxfood), ordered = TRUE)) %>%
  select(-x)

p.box.data.CHAET %>% unnest(outliers)


density.plot_CR_CHAET_1026 <-ggplot(p.box.data.CHAET) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = CHAET_plotting, aes(x = Chaet_mL.hr.bfactor, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (Chaetoceros) 92 DPF", 
                                     x = expression(Clearance~rate~"("~Chaetoceros~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey40", "grey40", "grey85", "grey85"))
density.plot_CR_CHAET_1026


pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_CR_CHAET_density_plot.pdf"), width = 5, height = 5)
density.plot_CR_CHAET_1026 # print the model diagnostics 
dev.off()


# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Tetraselmis (Ply)                  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


df_mean_PLY <- PLY_plotting %>%
  dplyr::group_by(pHxfood) %>% 
  dplyr::summarize(average = mean(Ply_mL.hr.bfactor)) %>%
  dplyr::ungroup()
p.box_PLY <- ggplot(PLY_plotting, aes(x = pHxfood, y = Ply_mL.hr.bfactor)) + geom_boxplot() + geom_point(data= df_mean_PLY, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.PLY <- layer_data(p.box_PLY) %>%
  select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
  dplyr::rename(mean = flipped_aes) %>% 
  dplyr::mutate(mean  = df_mean_PLY$average) %>% 
  mutate(pHxfood = factor(x, labels = levels(PLY_plotting$pHxfood), ordered = TRUE)) %>%
  select(-x)

p.box.data.PLY %>% unnest(outliers)


density.plot_CR_PLY_1026 <-ggplot(p.box.data.PLY) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = PLY_plotting, aes(x = Ply_mL.hr.bfactor, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (Tetraselmis/PLY) 92 DPF", 
                                     x = expression(Clearance~rate~"("~Tetraselmis~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey40", "grey40", "grey85", "grey85"))
density.plot_CR_PLY_1026

pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_CR_PLY_density_plot.pdf"), width = 5, height = 5)
density.plot_CR_PLY_1026 # print the model diagnostics 
dev.off()

# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Seston                             ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


df_mean_SESTON <- SESTON_plotting %>%
  dplyr::group_by(pHxfood) %>% 
  dplyr::summarize(average = mean(Seston_mL.hr.bfactor)) %>%
  dplyr::ungroup()
p.box_SESTON <- ggplot(SESTON_plotting, aes(x = pHxfood, y = Seston_mL.hr.bfactor)) + geom_boxplot() + geom_point(data= df_mean_SESTON, mapping = aes(x = pHxfood, y = average),
             color="red") 
p.box.data.SESTON <- layer_data(p.box_SESTON) %>%
  select(x, ymin, lower, middle, upper, ymax, outliers, flipped_aes) %>%
  dplyr::rename(mean = flipped_aes) %>% 
  dplyr::mutate(mean  = df_mean_SESTON$average) %>% 
  mutate(pHxfood = factor(x, labels = levels(SESTON_plotting$pHxfood), ordered = TRUE)) %>%
  select(-x)

p.box.data.SESTON %>% unnest(outliers)


density.plot_CR_SESTON_1026 <-ggplot(p.box.data.SESTON) +
                                # manually plot flipped boxplot
                                geom_segment(aes(x = ymin, xend = ymax, y = -0.15, yend = -0.15)) +
                                geom_rect(aes(xmin = lower, xmax = upper, ymin = -0.3, ymax = 0,  fill = pHxfood),color = "black") +
                                geom_point(data = . %>% unnest(outliers), aes(x = outliers, y = -0.15), color = "grey60", size = 1) +
                                # vertical lines at Q1 / Q2 / Q3
                                geom_vline(data = . %>% select(pHxfood, lower, mean, upper) %>% gather(key, value, -pHxfood), aes(xintercept = value)) +
                                # density plot
                                geom_density(data = SESTON_plotting, aes(x = Seston_mL.hr.bfactor, group=pHxfood, fill=pHxfood, ..scaled..), alpha=.4, adjust=1.5) +
                                #  theme
                                theme_classic() +
                                facet_grid(pHxfood ~ .) +
                                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.position = "none", plot.title = element_text(size=10))+
                                labs(title = "F1 Scallops: Clearance rates (seston) 92 DPF", 
                                     x = expression(Clearance~rate~"("~SESTONoceros~cells~mL^{-1}%.%~mm~shell~length^{-1}%.%hr^{-1}~")"),
                                     y = "Scaled density") +
                                scale_fill_manual(values=c("grey40", "grey40", "grey85", "grey85"))
density.plot_CR_SESTON_1026

pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/ClearanceRates/20211026_figs_tables/20211026_CR_SESTON_density_plot.pdf"), width = 5, height = 5)
density.plot_CR_SESTON_1026 # print the model diagnostics 
dev.off()

```