---
title: "seawater_chem"
author: "Samuel Gurr"
date: "11/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}

# LOAD PACKAGES
library(dplyr)
library(ggplot2)
library(kableExtra)
library(data.table)
library(stringr)
library(latex2exp)
library(Rmisc)
library(kableExtra)
library(ggpubr)

# SET WORKING DIRECTORY :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# setwd("C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis") # personal computer
  setwd("C:/Users/samuel.gurr/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis") # Work computer


# LOAD & FORMAT THE DATA 
# All data  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# chem    <- data.frame(read.csv(file="Data/Seawater_chemistry/Water_Chemistry_Scallops_2021.csv", header=T)) %>%  
#   dplyr::filter(!X  %in% c('Checking the system', 'RESPO', 'Tank Farm', 'Blue bucket check')) %>%  # ommit all occurances of 'checks' of the system
#   dplyr::rename(Date = ï..Date)
# chem$Date <- as.factor(gsub("/2021.*","", chem$Date))

# FOOD  OA CHALLENGE ONLY  ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# foodxOAchem    <- data.frame(read.csv(file="Data/Seawater_chemistry/Water_Chemistry_FoodxOA_Challenge.csv", header=T))[,c(1:20)] %>%  
#   dplyr::filter(!(Date %in% "10/12/2021" & Food.Treatment %in% 'Low')) %>% # omit 10/12/2021 measurements for the 'Low' Food treatment (check notebook, I think CO2 turned off overnight?) 
#   dplyr::filter(!X %in% 'checking the system') %>%  # ommit all occurances of 'checks' of the system
#   na.omit()
CarbChemfoodxOAchem    <- data.frame(read.csv(file="Data/Seawater_chemistry/MasterTable_FoodxOA.csv", header=T))

```

# ALL CHEMISTRY DATA  

### Figure (mean SE)
```{r all chem - figure, echo=FALSE}
Measured_values <- CarbChemfoodxOAchem[,c(1:6,10,12:14)] %>% dplyr::mutate(Calculation = 'Measured_values')

CO2SYS_TA.DIC   <- CarbChemfoodxOAchem %>% dplyr::select(c('Date', 'Fed_Unfed', 'pH', 'OA.pCO2.treat.', (contains("CO2SYS_TA.DIC")))) %>% dplyr::mutate(Calculation = 'TA.DIC')
colnames(CO2SYS_TA.DIC)[5:19] <- sub(".*DIC_", "", colnames(CO2SYS_TA.DIC)[5:19])

CO2SYS_TA.pH    <- CarbChemfoodxOAchem %>% dplyr::select(c('Date', 'Fed_Unfed', 'pH', 'OA.pCO2.treat.', (contains("CO2SYS_TA.pH"))))  %>% dplyr::mutate(Calculation = 'TA.pH')
colnames(CO2SYS_TA.pH)[5:19] <- sub(".*_TA.pH_", "", colnames(CO2SYS_TA.pH)[5:19])

CO2SYS_DIC.pH   <- CarbChemfoodxOAchem %>% dplyr::select(c('Date', 'Fed_Unfed', 'pH', 'OA.pCO2.treat.', (contains("CO2SYS_DIC.pH")))) %>% dplyr::mutate(Calculation = 'DIC.pH')
colnames(CO2SYS_DIC.pH)[5:19] <- sub(".*_DIC.pH_", "", colnames(CO2SYS_DIC.pH)[5:19])

CO2SYS_Master_CarbChem <- rbind(CO2SYS_TA.DIC, CO2SYS_TA.pH, CO2SYS_DIC.pH)
CO2SYS_Master_CarbChem <- CO2SYS_Master_CarbChem[!is.na(CO2SYS_Master_CarbChem$pH),] 

for(i in 5:(ncol(CO2SYS_Master_CarbChem)-1)){

columnName <- colnames(CO2SYS_Master_CarbChem)[i]

dat_fed <- CO2SYS_Master_CarbChem[!is.na(columnName),] %>% 
              dplyr::filter(!pH %in% 7) %>% 
              dplyr::filter(Fed_Unfed %in% 'fed') %>% 
              summarySE(measurevar=columnName, groupvars=c("Date","pH", "Calculation"))
P_fed <- ggplot(dat_fed, aes(x=Date, y=dat_fed[,5], colour=as.factor(pH), group=as.factor(pH))) + 
            geom_errorbar(aes(ymin=dat_fed[,5]-se, ymax=dat_fed[,5]+se), colour="black", width=.1, position=pd) +
            geom_line(position=pd) +
            theme_classic() +
            theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
            labs(title=paste('HIGH food supply:', columnName, sep = ' '), y = columnName) +
            geom_point(position=pd, size=3) +
            facet_wrap(~Calculation)
            #facet_wrap(~Calculation, scales = "free")



dat_unfed <- CO2SYS_Master_CarbChem[!is.na(columnName),] %>% 
              dplyr::filter(!pH %in% 7) %>% 
              dplyr::filter(Fed_Unfed %in% 'unfed') %>% 
              summarySE(measurevar=columnName, groupvars=c("Date","pH", "Calculation"))
P_unfed <- ggplot(dat_unfed, aes(x=Date, y=dat_unfed[,5], colour=as.factor(pH), group=as.factor(pH))) + 
            geom_errorbar(aes(ymin=dat_unfed[,5]-se, ymax=dat_unfed[,5]+se), colour="black", width=.1, position=pd) +
            geom_line(position=pd) +
            theme_classic() +
            theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
            labs(title=paste('LOW food supply:', columnName, sep = ' '), y = columnName) +
            geom_point(position=pd, size=3) +
            facet_wrap(~Calculation)


pdf(paste0( paste("C:/Users/samuel.gurr/Documents/Github_repositories/Airradians_OA-foodsupply/RAnalysis/Output/Water_Chemistry/plots/", columnName, ".pdf", sep = '')), width = 8, height = 10 )
print(ggarrange(P_fed, P_unfed, ncol = 1, nrow = 2))
dev.off()

}






# Total Alkalinity (Mean St Error)
TA_MeanSE <-  Measured_values[!is.na(Measured_values$TA_.mmol.kgSW.),] %>% 
  dplyr::filter(!pH %in% 7) %>% 
  summarySE(measurevar="TA_.mmol.kgSW.", groupvars=c("Date","pH", "Fed_Unfed")) %>% 
  dplyr::mutate(Measurement = 'TA_mmol.kgSW') %>% 
  dplyr::rename(value = TA_.mmol.kgSW.)
# Total CO2 (Mean St Error)
TACO2_MeanSE <-  Measured_values[!is.na(Measured_values$TCO2_.mmol.kgSW.),] %>% 
  dplyr::filter(!pH %in% 7) %>% 
  summarySE(measurevar="TCO2_.mmol.kgSW.", groupvars=c("Date","pH", "Fed_Unfed")) %>% 
  dplyr::mutate(Measurement = 'TCO2_mmol.kgSW') %>% 
  dplyr::rename(value = TCO2_.mmol.kgSW.)
#  pH Chosen scale (Mean St Error)
pChosenScale_MeanSE <-  Measured_values[!is.na(Measured_values$pH_Chosen_scale_.4.decimals.),] %>% 
  dplyr::filter(!pH %in% 7) %>% 
  summarySE(measurevar="pH_Chosen_scale_.4.decimals.", groupvars=c("Date","pH", "Fed_Unfed")) %>% 
  dplyr::mutate(Measurement = 'pH_Chosen_scale') %>% 
  dplyr::rename(value = pH_Chosen_scale_.4.decimals.)


master <- rbind(TA_MeanSE, TACO2_MeanSE, pChosenScale_MeanSE)

master$Date <- as.Date(master$Date,'%m/%d') # reformat the date here

pd <- position_dodge(0.1) # adjust the jitter for the different treatments   

Masterplot <- ggplot(master, aes(x=Date, y=value, colour=as.factor(pH), group=as.factor(pH))) + 
  geom_errorbar(aes(ymin=value-se, ymax=value+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_point(position=pd, size=3) +
  facet_wrap(~Measurement, scales = "free")
Masterplot

pdf("C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis/Output/Water_Chemistry/CarbChem_MeanSE_Timeseries.pdf", width=12, height=8)
print(Masterplot)
graphics.off()
```

### Table (mean SE)
```{r all chem table, echo=FALSE}
names(chem)
# Summary table chemistry
chemTable_byDate <- as.data.frame(chem[,c(1,6:8,14:20)] %>% 
    group_by(Date, OA_Treatment) %>%
    summarise_each(funs(mean))) %>% 
  na.omit() # a few missing TA measurments?
# chemTable_n <- chem[,c(1,6:8,14:20)] %>% 
#   group_by(Date, OA_Treatment) %>%
#   dplyr::summarise(n = n())

chemTable <- chemTable_byDate %>% 
    dplyr::select(-'Date') %>% 
    group_by(OA_Treatment) %>%
    summarise_each(funs(mean,sd,se=sd(.)/sqrt(n())))
chemTable_n <- chemTable_byDate %>% 
     group_by(OA_Treatment) %>%
     dplyr::summarise(n = n())

ChemTable_MeanSE <- data.frame(matrix(nrow = 3, ncol = 1))
ChemTable_MeanSE$pCO2_level   <-  c('Ambient','High','Mid')
ChemTable_MeanSE$N <- c(22,12,22)
ChemTable_MeanSE$Salinity <- paste(signif(chemTable$Salinity_mean,digits=3), signif(chemTable$Salinity_se,digits=3), sep="± ")
ChemTable_MeanSE$Temperature <- paste(signif(chemTable$t.oC._spec_mean,digits=3), signif(chemTable$t.oC._spec_se,digits=3), sep=" ± ")
ChemTable_MeanSE$pH <- paste(signif(chemTable$pH_out_MeasTemp_mean,digits=3), signif(chemTable$pH_out_MeasTemp_se,digits=3), sep=" ± ")
ChemTable_MeanSE$pCO2 <- paste(signif(chemTable$pCO2_out_.matm._MeasTemp_mean,digits=3), signif(chemTable$pCO2_out_.matm._MeasTemp_se,digits=3), sep=" ± ")
# ChemTable_MeanSE$DIC <- paste(chemTable$mean.DIC, chemTable$sem.DIC, sep=" Â± ")
ChemTable_MeanSE$TA <- paste(signif(chemTable$TA_.mmol.kgSW._mean,digits=3), signif(chemTable$TA_.mmol.kgSW._se,digits=3), sep=" ± ")
ChemTable_MeanSE$TCO2 <- paste(signif(chemTable$TCO2_.mmol.kgSW._mean,digits=3), signif(chemTable$TCO2_.mmol.kgSW._se,digits=3), sep=" ± ")
ChemTable_MeanSE$Aragonite.Sat <- paste(signif(chemTable$War_out_MeasTemp_mean,digits=3), signif(chemTable$War_out_MeasTemp_se,digits=3), sep=" ± ")
ChemTable_MeanSE$Calcite.Sat <- paste(signif(chemTable$Wca_out_MeasTemp_mean,digits=3), signif(chemTable$Wca_out_MeasTemp_se,digits=3), sep=" ± ")
ChemTable_MeanSE <- ChemTable_MeanSE[,-1] # view table


# write csv
#write.csv(Resp.Master_OM, "C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis/Output/Respiration/Calculated_Resp_Master.csv")
write.csv(ChemTable_MeanSE, "C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis/Output/Water_Chemistry/All_CarbChem_MeanSE.csv")


# show in markdown file
 ChemTable_MeanSE %>%  kbl(caption = "Seawater chemistry July 26, 2021 - Nov 23, 2021") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

# Food x OA Challenge (only!)

### Table (mean SE)


```{r food OA challenge chem table, echo=FALSE}
# Summary table chemistry
foodOA_table <- foodxOAchem[,c(3,4,6,11,13:14,16:20)] %>% 
    group_by(pH,Food.Treatment) %>%
    summarise_each(funs(mean,sd,se=sd(.)/sqrt(n())))
foodOA_table_n <- foodxOAchem[,c(3,4,6,11,13:14,16:20)] %>% 
  group_by(pH,Food.Treatment)  %>% 
  dplyr::summarise(n = n())

FoodXOA.Chem_MeanSE <- data.frame(matrix(nrow = 4, ncol = 1))
FoodXOA.Chem_MeanSE$pCO2_level   <-  c('High','High','Low','Low')
FoodXOA.Chem_MeanSE$Food_supply  <-  c('High','Low','High','Low')
FoodXOA.Chem_MeanSE$pHXfood <- paste(foodOA_table$pH,foodOA_table$Food.Treatment, sep = '*')
FoodXOA.Chem_MeanSE$N <- c(21,16,21,16)
FoodXOA.Chem_MeanSE$Salinity <- paste(signif(foodOA_table$Salinity_mean,digits=3), signif(foodOA_table$Salinity_se,digits=3), sep="± ")
FoodXOA.Chem_MeanSE$Temperature <- paste(signif(foodOA_table$t.oC..of.bucket_mean,digits=3), signif(foodOA_table$t.oC..of.bucket_se,digits=3), sep=" ± ")
FoodXOA.Chem_MeanSE$DO <- paste(signif(foodOA_table$DO.mg.L_mean,digits=3), signif(foodOA_table$DO.mg.L_se,digits=3), sep=" ± ")
FoodXOA.Chem_MeanSE$pH <- paste(signif(foodOA_table$pH.out_mean,digits=3), signif(foodOA_table$pH.out_se,digits=3), sep=" ± ")
FoodXOA.Chem_MeanSE$pCO2 <- paste(signif(foodOA_table$pCO2.out..matm._mean,digits=3), signif(foodOA_table$pCO2.out..matm._se,digits=3), sep=" ± ")
# FoodXOA.Chem_MeanSE$DIC <- paste(foodOA_table$mean.DIC, foodOA_table$sem.DIC, sep=" Â± ")
FoodXOA.Chem_MeanSE$TA <- paste(signif(foodOA_table$TA..mmol.kgSW._mean,digits=3), signif(foodOA_table$TA..mmol.kgSW._se,digits=3), sep=" ± ")
FoodXOA.Chem_MeanSE$Aragonite.Sat <- paste(signif(foodOA_table$WAr.out_mean,digits=3), signif(foodOA_table$WAr.out_se,digits=3), sep=" ± ")
FoodXOA.Chem_MeanSE$Calcite.Sat <- paste(signif(foodOA_table$WCa.out_mean,digits=3), signif(foodOA_table$WCa.out_se,digits=3), sep=" ± ")
FoodXOA.Chem_MeanSE <- FoodXOA.Chem_MeanSE[,-1] # view table


# write csv
#write.csv(Resp.Master_OM, "C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis/Output/Respiration/Calculated_Resp_Master.csv")
write.csv(FoodXOA.Chem_MeanSE, "C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis/Output/Water_Chemistry/FoodxOAChallenge_CarbChem_MeanSE.csv")


# show in markdown file
 FoodXOA.Chem_MeanSE %>%  kbl(caption = "Seawater chemistry Food x OA Challenge (only)") %>%
  kable_classic(full_width = F, html_font = "Cambria")
 
```
